name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main

jobs:
  deploy_to_dev:
    name: Dev
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/deploy-to-dev.yaml
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
  
  deploy_to_prod:
    name: Prod
    permissions:
      contents: write
      id-token: write
    needs: deploy_to_dev
    uses: ./.github/workflows/deploy-to-prod.yaml
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
