name: Sanity Build

on: [pull_request]

jobs:
  sanity-build:
    strategy:
      fail-fast: false
      matrix:
        apps: [frontend, server]
    name: ${{ matrix.apps }} Sanity Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ${{ matrix.apps }}/package-lock.json
      - name: Install ${{ matrix.apps }} dependencies
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          npm ci --prefer-offline
      - name: Lint ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          npm run lint
      - name: Test ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          npm test
      - name: Build ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          npm run build
